name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r src/docker/requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src --count --max-line-length=88 --statistics

      - name: Run tests
        run: |
          python -m unittest discover -s tests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/iris-api
          docker build -t $IMAGE_NAME:latest -f src/docker/Dockerfile src
          docker push $IMAGE_NAME:latest

      - name: Make deploy script executable
        run: chmod +x src/docker/deploy.sh

      - name: Run deploy script
        run: ./src/docker/deploy.sh
